name: CDK Deploy

on:
  push:
    paths:
      - "cdk-s3-ts/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:16
      options: --user=root --workdir=/github/workspace

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "cdk-s3-ts"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: yarn install

      - name: Synthesize CDK stack
        run: cdk synth

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never

      - name: Run tests
        run: npm test
