name: CDK Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI and CDK
        run: |
          apt-get update
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install dependencies
        working-directory: s3-lambda-ddb
        run: yarn install

      - name: Build
        working-directory: s3-lambda-ddb
        run: yarn build

      - name: Deploy CDK stack
        working-directory: s3-lambda-ddb
        run: cdk deploy --require-approval never

      - name: Run tests
        run: npm test
